apiVersion: v1
kind: Pod
metadata:
  name: nodeaff-2
spec:
  containers:
    - name: contnodeaff2
      image: httpd

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
# ( on nodes witout Large label)              
              - key: size
                operator: NotIn
                values:
                  - Large
#                  - Medium
# ( on nodes wit size label set)              
#              - key: size
#                operator: Exists
