apiVersion: v1
kind: Pod
metadata:
  name: nodeaff-1
spec:
  containers:
    - name: contnodeaff1
      image: httpd

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large
#                  - Medium
